apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: cpiflow-serving-pipeline
  annotations:
    scenarios.ai.sap.com/name: "CPIFLOW Optimizer PRO"
    scenarios.ai.sap.com/description: "FastAPI on KServe"
    executables.ai.sap.com/name: "cpiflow-model-serving"
    executables.ai.sap.com/description: "All-in-one CPI classifier API"
    artifacts.ai.sap.com/cpiflowmodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "cpiflow-optimizer-pro"
    ai.sap.com/version: "6.5"   # bump to force a new Knative Revision
spec:
  inputs:
    artifacts:
      - name: cpiflowmodel
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    kind: InferenceService
    metadata:
      name: cpiflow-serving
      annotations: |-
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/targetBurstCapacity: "0"
      labels: |-
        ai.sap.com/resourcePlan: starter
    spec: |-
      predictor:
        minReplicas: 1
        maxReplicas: 2
        containers:
          - name: kserve-container
            image: docker.io/balakalyandocker/cpiflow-serve:py312-v1
            command: ["/bin/sh","-lc"]
            args:
              - |
                set -e
                export MODEL_MOUNT_DIR="${MODEL_MOUNT_DIR:-/mnt/models}"

                echo "=== DEBUG: initial mount ==="
                ls -l "$MODEL_MOUNT_DIR" || true

                # Descend through up to TWO wrapper directories if there's exactly one entry each time
                for i in 1 2; do
                  if [ -d "$MODEL_MOUNT_DIR" ]; then
                    cnt="$(ls -1 "$MODEL_MOUNT_DIR" 2>/dev/null | wc -l | tr -d ' ')"
                    if [ "$cnt" = "1" ]; then
                      only="$(ls -1 "$MODEL_MOUNT_DIR" 2>/dev/null)"
                      if [ -d "$MODEL_MOUNT_DIR/$only" ]; then
                        MODEL_MOUNT_DIR="$MODEL_MOUNT_DIR/$only"
                        echo "=== DEBUG: descended to: $MODEL_MOUNT_DIR"
                        continue
                      fi
                    fi
                  fi
                  break
                done

                # Normalize artifact-named file -> model.pkl
                if [ -f "$MODEL_MOUNT_DIR/cpiflowmodel" ] && [ ! -f "$MODEL_MOUNT_DIR/model.pkl" ]; then
                  cp "$MODEL_MOUNT_DIR/cpiflowmodel" "$MODEL_MOUNT_DIR/model.pkl"
                  echo "=== DEBUG: normalized cpiflowmodel -> model.pkl"
                fi

                echo "=== DEBUG: final model dir ==="
                ls -l "$MODEL_MOUNT_DIR" || true

                exec uvicorn --app-dir /app/src serve_cpiflow_kserve:app \
                  --host 0.0.0.0 --port ${PORT:-8080}
            env:
              - name: STORAGE_URI
                value: "{{inputs.artifacts.cpiflowmodel}}"
              - name: MODEL_MOUNT_DIR
                value: "/mnt/models"
              - name: LABELS_DIR
                value: "/mnt/labels"
            ports:
              - name: http1
                containerPort: 8080
                protocol: TCP
            readinessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 2
              periodSeconds: 5
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "1"
                memory: "1Gi"
