apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: cpiflow-serving-pipeline
  annotations:
    scenarios.ai.sap.com/name: "CPIFLOW Optimizer PRO"
    scenarios.ai.sap.com/description: "FastAPI on KServe with drift, signatures, forecast, explain, prioritize, label"
    executables.ai.sap.com/name: "cpiflow-model-serving"
    executables.ai.sap.com/description: "All-in-one CPI classifier API"
    artifacts.ai.sap.com/cpiflowmodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "cpiflow-optimizer-pro"
    ai.sap.com/version: "6.0"
spec:
  inputs:
    artifacts:
      - name: cpiflowmodel
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: milton-credentials
        minReplicas: 1
        maxReplicas: 3
        containers:
          - name: kserve-container
            image: docker.io/balakalyandocker/cpilog-serve:py312-v1
            command: ["/bin/sh","-c"]
            args:
              - >
                set -e;
                uvicorn --app-dir /app/src serve_cpiflow_kserve:app
                --host 0.0.0.0 --port ${PORT:-8080}
            env:
              - name: STORAGE_URI
                value: "{{inputs.artifacts.cpiflowmodel}}"
              - name: LABELS_DIR
                value: "/mnt/labels"
            ports:
              - name: http1
                containerPort: 8080
                protocol: TCP
