apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: cpiflow-serving-pipeline
  annotations:
    scenarios.ai.sap.com/name: "CPIFLOW Optimizer PRO"
    scenarios.ai.sap.com/description: "Serving CPIFLOW classifier via KServe"
    executables.ai.sap.com/name: "cpiflow-model-serving"
    executables.ai.sap.com/description: "FastAPI server for CPIFLOW classifier"
    artifacts.ai.sap.com/cpiflowmodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "cpiflow-optimizer-pro"
    ai.sap.com/version: "7.6"                # bump to force NEW Knative Revision
spec:
  inputs:
    artifacts:
      - name: cpiflowmodel
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        # If your image is private, keep this. If it's public, you can remove.
        imagePullSecrets:
          - name: milton-credentials
        minReplicas: 1
        maxReplicas: 2
        containers:
        - name: kserve-container
          image: docker.io/balakalyandocker/cpiflow-serve:py312-v1
          imagePullPolicy: Always
          # Name the port "http1" so Knative/Istio detect it cleanly
          ports:
            - name: http1
              containerPort: 8080
              protocol: TCP
          command: ["/bin/sh","-c"]
          args:
            - >
              set -e &&
              uvicorn --app-dir /app/src serve_cpiflow_kserve:app
              --host 0.0.0.0 --port ${PORT:-8080}
          env:
            - name: STORAGE_URI
              value: "{{inputs.artifacts.cpiflowmodel}}"
            # Knative injects PORT. We still default to 8080 for local parity.
            - name: MODEL_MOUNT_DIR
              value: "/mnt/models"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
