apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cpiflow-training-pipeline
  annotations:
    scenarios.ai.sap.com/name: "CPIFLOW Optimizer"
    scenarios.ai.sap.com/description: "Train CPI log classifier (LR/SGD) with drift baselines & insights"
    executables.ai.sap.com/name: "cpiflow-model-training"
    executables.ai.sap.com/description: "Outputs model.pkl"
    artifacts.ai.sap.com/cpiflowdataset.kind: "dataset"
    artifacts.ai.sap.com/cpiflowmodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "cpiflow-optimizer-pro"
    ai.sap.com/version: "6.0"
spec:
  imagePullSecrets:
    - name: milton-credentials
  entrypoint: mypipeline
  arguments:
    parameters:
      - name: TARGET_COLUMN
        value: "CUSTOM_STATUS"
      - name: DATA_FILE
        value: "cpi_logs_500.csv"
      - name: TRAINER
        value: "LR"
      - name: FINETUNE
        value: "0"
  templates:
    - name: mypipeline
      inputs:
        artifacts:
          - name: cpiflowdataset
            path: /app/data
          - name: prevmodel
            path: /app/prev/prev_model.pkl
            optional: true
      outputs:
        artifacts:
          - name: cpiflowmodel
            globalName: cpiflowmodel
            path: /app/model/model.pkl
            archive:
              none: {}
      container:
        image: docker.io/balakalyandocker/cpilog-train:py312-v1
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-c"]
        env:
          - name: TARGET_COLUMN
            value: "{{workflow.parameters.TARGET_COLUMN}}"
          - name: DATA_PATH
            value: "/app/data/{{workflow.parameters.DATA_FILE}}"
          - name: MODEL_DIR
            value: "/app/model"
          - name: MODEL_PATH
            value: "/app/model/model.pkl"
          - name: TRAINER
            value: "{{workflow.parameters.TRAINER}}"
          - name: FINETUNE_MODE
            value: "{{workflow.parameters.FINETUNE}}"
          - name: PREV_MODEL_PATH
            value: "/app/prev/prev_model.pkl"
        args:
          - >
            set -euo pipefail;
            echo '--- /app/data ---'; ls -la /app/data || true;
            mkdir -p /app/model;
            if [ ! -f /app/prev/prev_model.pkl ]; then export FINETUNE_MODE=0; fi;
            python /app/src/train_cpiflow_pipeline.py;
            echo '--- /app/model ---'; ls -la /app/model || true;
            # Final guard to avoid artifact-missing:
            test -f /app/model/model.pkl || { echo "model.pkl missing"; exit 2; }
